name: Spells

author: Me!!!

main: Spells.Spells

commands: 
  restore:
    description: Restore health 
    usage: /restore [optional user] 
  avadakedavra:
    description: kills the user
    usage: /avadakedavra [optional user] 
  expectopatronum:
    description: brings the patronum of the player
    usage: /expectopatronum 

version: 0.0.1
